server: server.c utils.h utils.c config.h cmd_handle.c cmd_handle.h socket_utils.c socket_utils.h path_utils.c path_utils.c
	gcc -o server server.c utils.c cmd_handle.c socket_utils.c path_utils.c

clean:
	rm server